server:
  port: 8083

spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://localhost:3306/banking_system
    username: root
    password: Akash@2003
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


  cache:
    type: redis

  data:
    redis:
      host: redis-13050.crce179.ap-south-1-1.ec2.cloud.redislabs.com
      port: 13050
      password: dXVNWpG9WoQSbOgIvpPcfxb50PQQTtMD
      timeout: 3000


eureka :
  client :
    service-url :
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
jwt:
  secret: U2VjdXJlS2V5Rm9yQmFua2luZ0FwcFNob3VsZEJlQmFzZTY0
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true